apiVersion: v2
name: papercups
description: Papercups is an open source live customer chat web app

type: application
version: 0.1.0
appVersion: 0.1.0

dependencies:
  - name: postgresql
    version: 9.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - papercups-database
