apiVersion: v2
name: papercups
description: An open source live customer chat web app
icon: https://raw.githubusercontent.com/papercups-io/papercups/master/assets/public/logo.svg
type: application
version: 0.1.0
appVersion: 0.1.0

dependencies:
  - name: postgresql
    version: 9.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - papercups-database
